/// Auto-generated routes file.
/// DO NOT EDIT MANUALLY - This file is generated by Kiro CLI.
library;

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../features/home/home_screen.dart';

import '../modules/notifications/presentation/screens/notifications_screen.dart';
import '../modules/chat/presentation/screens/chat_list_screen.dart';
import '../modules/chat/presentation/screens/chat_detail_screen.dart';
import '../modules/tracking/presentation/screens/tracking_screen.dart';
import '../modules/tracking/presentation/screens/map_screen.dart';
import '../modules/auth/presentation/screens/login_screen.dart';
import '../modules/auth/presentation/screens/signup_screen.dart';
import '../modules/auth/presentation/screens/forgot_password_screen.dart';
import '../modules/auth/presentation/screens/verify_otp_screen.dart';
import '../modules/payments/presentation/screens/payments_screen.dart';
import '../modules/payments/presentation/screens/checkout_screen.dart';
import '../modules/wallet/presentation/screens/wallet_screen.dart';
import '../modules/wallet/presentation/screens/add_money_screen.dart';
import '../modules/wallet/presentation/screens/transactions_screen.dart';
import '../modules/wallet/presentation/screens/transaction_detail_screen.dart';
import '../modules/booking/presentation/screens/bookings_screen.dart';
import '../modules/booking/presentation/screens/create_booking_screen.dart';
import '../modules/booking/presentation/screens/booking_detail_screen.dart';
import '../modules/profile/presentation/screens/profile_screen.dart';
import '../modules/profile/presentation/screens/edit_profile_screen.dart';
import '../modules/profile/presentation/screens/settings_screen.dart';

/// App route paths.
class AppRoutes {
  AppRoutes._();

  static const String home = '/';
  static const String notifications = '/notifications';
  static const String chat_list = '/chat';
  static const String chat_detail = '/chat/:chatId';
  static const String tracking = '/tracking';
  static const String map = '/tracking/map';
  static const String login = '/login';
  static const String signup = '/signup';
  static const String forgot_password = '/forgot-password';
  static const String verify_otp = '/verify-otp';
  static const String payments = '/payments';
  static const String checkout = '/payments/checkout';
  static const String wallet = '/wallet';
  static const String add_money = '/wallet/add-money';
  static const String transactions = '/wallet/transactions';
  static const String transaction_detail = '/wallet/transaction/:id';
  static const String bookings = '/bookings';
  static const String create_booking = '/bookings/create';
  static const String booking_detail = '/bookings/:id';
  static const String profile = '/profile';
  static const String edit_profile = '/profile/edit';
  static const String settings = '/profile/settings';
}

/// Auto-generated app router.
final appRouter = GoRouter(
  initialLocation: AppRoutes.home,
  debugLogDiagnostics: true,
  routes: [
    GoRoute(
      path: AppRoutes.home,
      name: 'home',
      builder: (context, state) => const HomeScreen(),
    ),
    GoRoute(
      path: AppRoutes.notifications,
      name: 'notifications',
      builder: (context, state) => const NotificationsScreen(),
    ),
    GoRoute(
      path: AppRoutes.chat_list,
      name: 'chatList',
      builder: (context, state) => const ChatListScreen(),
    ),
    GoRoute(
      path: AppRoutes.chat_detail,
      name: 'chatDetail',
      builder: (context, state) {
        final chatId = state.pathParameters['chatId'] ?? '';
        return ChatDetailScreen(chatId: chatId);
      },
    ),
    GoRoute(
      path: AppRoutes.tracking,
      name: 'tracking',
      builder: (context, state) => const TrackingScreen(),
    ),
    GoRoute(
      path: AppRoutes.map,
      name: 'map',
      builder: (context, state) => const MapScreen(),
    ),
    GoRoute(
      path: AppRoutes.login,
      name: 'login',
      builder: (context, state) => const LoginScreen(),
    ),
    GoRoute(
      path: AppRoutes.signup,
      name: 'signup',
      builder: (context, state) => const SignupScreen(),
    ),
    GoRoute(
      path: AppRoutes.forgot_password,
      name: 'forgotPassword',
      builder: (context, state) => const ForgotPasswordScreen(),
    ),
    GoRoute(
      path: AppRoutes.verify_otp,
      name: 'verifyOtp',
      builder: (context, state) {
        final phoneNumber = state.uri.queryParameters['phone'] ?? '';
        return VerifyOtpScreen(phoneNumber: phoneNumber);
      },
    ),
    GoRoute(
      path: AppRoutes.payments,
      name: 'payments',
      builder: (context, state) => const PaymentsScreen(),
    ),
    GoRoute(
      path: AppRoutes.checkout,
      name: 'checkout',
      builder: (context, state) {
        final amountStr = state.uri.queryParameters['amount'] ?? '0.0';
        final amount = double.tryParse(amountStr) ?? 0.0;
        final orderId = state.uri.queryParameters['orderId'];
        return CheckoutScreen(amount: amount, orderId: orderId);
      },
    ),
    GoRoute(
      path: AppRoutes.wallet,
      name: 'wallet',
      builder: (context, state) => const WalletScreen(),
    ),
    GoRoute(
      path: AppRoutes.add_money,
      name: 'addMoney',
      builder: (context, state) => const AddMoneyScreen(),
    ),
    GoRoute(
      path: AppRoutes.transactions,
      name: 'transactions',
      builder: (context, state) => const TransactionsScreen(),
    ),
    GoRoute(
      path: AppRoutes.transaction_detail,
      name: 'transactionDetail',
      builder: (context, state) {
        final transactionId = state.pathParameters['id'] ?? '';
        return TransactionDetailScreen(transactionId: transactionId);
      },
    ),
    GoRoute(
      path: AppRoutes.bookings,
      name: 'bookings',
      builder: (context, state) => const BookingsScreen(),
    ),
    GoRoute(
      path: AppRoutes.create_booking,
      name: 'createBooking',
      builder: (context, state) => const CreateBookingScreen(),
    ),
    GoRoute(
      path: AppRoutes.booking_detail,
      name: 'bookingDetail',
      builder: (context, state) {
        final bookingId = state.pathParameters['id'] ?? '';
        return BookingDetailScreen(bookingId: bookingId);
      },
    ),
    GoRoute(
      path: AppRoutes.profile,
      name: 'profile',
      builder: (context, state) => const ProfileScreen(),
    ),
    GoRoute(
      path: AppRoutes.edit_profile,
      name: 'editProfile',
      builder: (context, state) => const EditProfileScreen(),
    ),
    GoRoute(
      path: AppRoutes.settings,
      name: 'settings',
      builder: (context, state) => const SettingsScreen(),
    ),
  ],
  errorBuilder: (context, state) => Scaffold(
    appBar: AppBar(title: const Text('Error')),
    body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(Icons.error_outline, size: 64, color: Colors.grey),
          const SizedBox(height: 16),
          Text('Page not found: ${state.uri.path}'),
          const SizedBox(height: 16),
          ElevatedButton(
            onPressed: () => context.go(AppRoutes.home),
            child: const Text('Go Home'),
          ),
        ],
      ),
    ),
  ),
);
