/// Environment configuration generator.
library;

import '../utils/file_utils.dart';

/// Generates environment configuration files.
class EnvConfigGenerator {
  final String projectPath;
  final bool useFirebase;

  EnvConfigGenerator({
    required this.projectPath,
    this.useFirebase = false,
  });

  /// Generate environment configuration files.
  Future<void> generateEnvConfigs() async {
    // Generate .env.dev
    await _generateEnvFile('dev', {
      'ENV': 'development',
      'API_BASE_URL': 'https://api-dev.example.com',
      'DEBUG': 'true',
      if (useFirebase) 'FIREBASE_ENABLED': 'true',
    });

    // Generate .env.staging
    await _generateEnvFile('staging', {
      'ENV': 'staging',
      'API_BASE_URL': 'https://api-staging.example.com',
      'DEBUG': 'true',
      if (useFirebase) 'FIREBASE_ENABLED': 'true',
    });

    // Generate .env.prod
    await _generateEnvFile('prod', {
      'ENV': 'production',
      'API_BASE_URL': 'https://api.example.com',
      'DEBUG': 'false',
      if (useFirebase) 'FIREBASE_ENABLED': 'true',
    });

    // Generate .env.example
    await _generateEnvFile('example', {
      'ENV': 'development',
      'API_BASE_URL': 'https://api-dev.example.com',
      'DEBUG': 'true',
      if (useFirebase) 'FIREBASE_ENABLED': 'true',
    });

    // Generate environment loader
    await _generateEnvLoader();
  }

  /// Generate an environment file.
  Future<void> _generateEnvFile(String env, Map<String, String> values) async {
    final content = StringBuffer();
    content.writeln('# Environment: $env');
    content.writeln('# Generated by Kiro CLI');
    content.writeln('# DO NOT commit actual values to version control');
    content.writeln();

    for (final entry in values.entries) {
      content.writeln('${entry.key}=${entry.value}');
    }

    final fileName = env == 'example' ? '.env.example' : '.env.$env';
    await FileUtils.writeFile(
      FileUtils.join(projectPath, fileName),
      content.toString(),
    );
  }

  /// Generate environment loader class.
  Future<void> _generateEnvLoader() async {
    final content = '''
/// Environment configuration loader.
library;

import 'dart:io';

import 'package:flutter/foundation.dart';

/// Environment configuration.
class EnvConfig {
  EnvConfig._();

  static EnvConfig? _instance;
  static EnvConfig get instance {
    _instance ??= EnvConfig._();
    return _instance!;
  }

  /// Load environment variables from .env file.
  static Future<void> load({String env = 'dev'}) async {
    try {
      final envFile = File('.env.\$env');
      if (await envFile.exists()) {
        final lines = await envFile.readAsLines();
        for (final line in lines) {
          if (line.trim().isEmpty || line.startsWith('#')) {
            continue;
          }
          final parts = line.split('=');
          if (parts.length == 2) {
            final key = parts[0].trim();
            final value = parts[1].trim();
            instance._values[key] = value;
          }
        }
      }
    } catch (e) {
      if (kDebugMode) {
        print('Warning: Could not load .env file: \$e');
      }
    }
  }

  final Map<String, String> _values = {};

  /// Get environment variable.
  String? get(String key) => _values[key];

  /// Get environment variable with default.
  String getOrElse(String key, String defaultValue) {
    return _values[key] ?? defaultValue;
  }

  /// Get boolean environment variable.
  bool getBool(String key, {bool defaultValue = false}) {
    final value = _values[key];
    if (value == null) return defaultValue;
    return value.toLowerCase() == 'true';
  }

  /// Get integer environment variable.
  int? getInt(String key) {
    final value = _values[key];
    if (value == null) return null;
    return int.tryParse(value);
  }

  /// Get double environment variable.
  double? getDouble(String key) {
    final value = _values[key];
    if (value == null) return null;
    return double.tryParse(value);
  }

  /// Current environment.
  String get env => getOrElse('ENV', 'development');

  /// API base URL.
  String get apiBaseUrl => getOrElse('API_BASE_URL', 'https://api.example.com');

  /// Debug mode.
  bool get isDebug => getBool('DEBUG', defaultValue: false);

  /// Firebase enabled.
  bool get isFirebaseEnabled => getBool('FIREBASE_ENABLED', defaultValue: false);
}
''';

    await FileUtils.writeFile(
      FileUtils.join(projectPath, 'lib', 'config', 'env_config.dart'),
      content,
    );
  }
}


