/// Provider registry generator for auto-registering module providers.
library;

import 'module_metadata.dart';

/// Generates provider registry from module metadata.
class ProviderRegistryGenerator {
  /// Generate provider registry file content.
  static String generateProviderRegistry({
    required List<ModuleMetadata> modules,
    required String appName,
  }) {
    final buffer = StringBuffer();

    buffer.writeln('/// Auto-generated provider registry.');
    buffer.writeln('/// DO NOT EDIT MANUALLY - This file is generated by Kiro CLI.');
    buffer.writeln('library;');
    buffer.writeln();
    buffer.writeln("import 'package:flutter_riverpod/flutter_riverpod.dart';");
    buffer.writeln();

    // Collect all unique provider imports
    final providerImports = <String>{};
    for (final module in modules) {
      for (final provider in module.providers) {
        final importPath = _getProviderImportPath(module.name, provider);
        providerImports.add(importPath);
      }
    }

    // Write imports
    for (final importPath in providerImports) {
      buffer.writeln("import '$importPath';");
    }
    buffer.writeln();

    // Generate provider list
    buffer.writeln('/// List of all module providers.');
    buffer.writeln('/// This is used to register all providers at app startup.');
    buffer.writeln('final List<Provider> moduleProviders = [');
    
    for (final module in modules) {
      if (module.providers.isEmpty) continue;
      
      buffer.writeln('  // ${module.displayName} module');
      for (final provider in module.providers) {
        final providerName = provider.name;
        buffer.writeln('  $providerName,');
      }
      buffer.writeln();
    }
    
    buffer.writeln('];');
    buffer.writeln();

    // Generate provider override function
    buffer.writeln('/// Override providers for testing.');
    buffer.writeln('List<Override> getProviderOverrides() {');
    buffer.writeln('  return [');
    buffer.writeln('    // Add provider overrides here for testing');
    buffer.writeln('  ];');
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generate provider setup function for main.dart.
  static String generateProviderSetup({
    required List<ModuleMetadata> modules,
  }) {
    if (modules.isEmpty) {
      return '''
// No modules with providers
''';
    }

    final buffer = StringBuffer();
    buffer.writeln('// Register all module providers');
    buffer.writeln('final container = ProviderContainer(');
    buffer.writeln('  overrides: getProviderOverrides(),');
    buffer.writeln(');');

    return buffer.toString();
  }

  static String _getProviderImportPath(String moduleName, ModuleProvider provider) {
    if (provider.path != null) {
      return '../modules/$moduleName/${provider.path}';
    }
    // Default path based on provider name
    return '../modules/$moduleName/presentation/providers/${_toSnakeCase(provider.name)}.dart';
  }

  static String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceAll(RegExp(r'^_'), '')
        .toLowerCase();
  }
}


