/// Route generator for auto-generating routes from module metadata.
library;

import 'module_metadata.dart';

/// Generate routes file from module metadata.
class RouteGenerator {
  /// Generate routes.dart content from module metadata.
  static String generateRoutes({
    required List<ModuleMetadata> modules,
    required String appName,
  }) {
    return generateRoutesWithConfig(
      modules: modules,
      appName: appName,
      includeSplash: false,
      includeOnboarding: false,
      hasAuth: modules.any((m) => m.name == 'auth'),
      bottomNavTabs: [],
    );
  }

  /// Generate routes with full app flow configuration.
  static String generateRoutesWithConfig({
    required List<ModuleMetadata> modules,
    required String appName,
    required bool includeSplash,
    required bool includeOnboarding,
    required bool hasAuth,
    required List<String> bottomNavTabs,
  }) {
    final buffer = StringBuffer();
    
    // Imports
    buffer.writeln("/// Auto-generated routes file.");
    buffer.writeln("/// DO NOT EDIT MANUALLY - This file is generated by Kiro CLI.");
    buffer.writeln("library;");
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:go_router/go_router.dart';");
    if (includeOnboarding || hasAuth) {
      buffer.writeln("import 'package:shared_preferences/shared_preferences.dart';");
    }
    buffer.writeln();
    
    // Conditional imports
    if (includeSplash) {
      buffer.writeln("import '../features/splash/splash_screen.dart';");
    }
    if (includeOnboarding) {
      buffer.writeln("import '../features/onboarding/onboarding_screen.dart';");
    }
    buffer.writeln("import '../features/main_shell/main_shell.dart';");
    buffer.writeln("import '../features/home/home_screen.dart';");
    buffer.writeln();
    
    // Module imports
    for (final module in modules) {
      for (final route in module.routes) {
        final screenPath = _getScreenImportPath(module.name, route.screen);
        buffer.writeln("import '$screenPath';");
      }
    }
    buffer.writeln();
    
    // Route constants
    buffer.writeln("/// App route paths.");
    buffer.writeln("class AppRoutes {");
    buffer.writeln("  AppRoutes._();");
    buffer.writeln();
    
    buffer.writeln("  static const String initial = '/';");
    if (includeSplash) {
      buffer.writeln("  static const String splash = '/splash';");
    }
    if (includeOnboarding) {
      buffer.writeln("  static const String onboarding = '/onboarding';");
    }
    if (hasAuth) {
      buffer.writeln("  static const String login = '/login';");
      buffer.writeln("  static const String signup = '/signup';");
      buffer.writeln("  static const String forgot_password = '/forgot-password';");
      buffer.writeln("  static const String verify_otp = '/verify-otp';");
    }
    buffer.writeln("  static const String main = '/main';");
    buffer.writeln("  static const String home = '/';");
    
    // Module routes
    for (final module in modules) {
      for (final route in module.routes) {
        // Skip auth routes as they're handled above
        if (module.name == 'auth' && ['login', 'signup', 'forgotPassword', 'verifyOtp'].contains(route.name)) {
          continue;
        }
        final constantName = _toConstantName(route.name);
        buffer.writeln("  static const String $constantName = '${route.path}';");
      }
    }
    
    buffer.writeln("}");
    buffer.writeln();
    
    // Router generation with redirects
    buffer.writeln("/// Auto-generated app router.");
    buffer.writeln("final appRouter = GoRouter(");
    buffer.writeln("  initialLocation: AppRoutes.initial,");
    buffer.writeln("  debugLogDiagnostics: true,");
    if (includeOnboarding || hasAuth) {
      buffer.writeln("  redirect: _handleRedirect,");
    }
    buffer.writeln("  routes: [");
    
    // Splash route
    if (includeSplash) {
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.splash,");
      buffer.writeln("      name: 'splash',");
      buffer.writeln("      builder: (context, state) => const SplashScreen(),");
      buffer.writeln("    ),");
    }
    
    // Onboarding route
    if (includeOnboarding) {
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.onboarding,");
      buffer.writeln("      name: 'onboarding',");
      buffer.writeln("      builder: (context, state) => const OnboardingScreen(),");
      buffer.writeln("    ),");
    }
    
    // Auth routes
    if (hasAuth) {
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.login,");
      buffer.writeln("      name: 'login',");
      buffer.writeln("      builder: (context, state) => const LoginScreen(),");
      buffer.writeln("    ),");
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.signup,");
      buffer.writeln("      name: 'signup',");
      buffer.writeln("      builder: (context, state) => const SignupScreen(),");
      buffer.writeln("    ),");
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.forgot_password,");
      buffer.writeln("      name: 'forgotPassword',");
      buffer.writeln("      builder: (context, state) => const ForgotPasswordScreen(),");
      buffer.writeln("    ),");
      buffer.writeln("    GoRoute(");
      buffer.writeln("      path: AppRoutes.verify_otp,");
      buffer.writeln("      name: 'verifyOtp',");
      buffer.writeln("      builder: (context, state) {");
      buffer.writeln("        final phoneNumber = state.uri.queryParameters['phone'] ?? '';");
      buffer.writeln("        return VerifyOtpScreen(phoneNumber: phoneNumber);");
      buffer.writeln("      },");
      buffer.writeln("    ),");
    }
    
    // Main shell route
    buffer.writeln("    GoRoute(");
    buffer.writeln("      path: AppRoutes.main,");
    buffer.writeln("      name: 'main',");
    buffer.writeln("      builder: (context, state) => const MainShell(),");
    buffer.writeln("    ),");
    
    // Home route (inside main shell)
    buffer.writeln("    GoRoute(");
    buffer.writeln("      path: AppRoutes.home,");
    buffer.writeln("      name: 'home',");
    buffer.writeln("      builder: (context, state) => const HomeScreen(),");
    buffer.writeln("    ),");
    
    // Module routes (excluding auth routes already added)
    for (final module in modules) {
      for (final route in module.routes) {
        // Skip auth routes as they're handled above
        if (module.name == 'auth' && ['login', 'signup', 'forgotPassword', 'verifyOtp'].contains(route.name)) {
          continue;
        }
        
        buffer.writeln("    GoRoute(");
        buffer.writeln("      path: AppRoutes.${_toConstantName(route.name)},");
        buffer.writeln("      name: '${route.name}',");
        
        if (route.requiresAuth) {
          buffer.writeln("      redirect: (context, state) {");
          buffer.writeln("        // TODO: Add auth check");
          buffer.writeln("        return null;");
          buffer.writeln("      },");
        }
        
        // Handle screens with required parameters
        final hasPathParams = route.path.contains(':');
        final needsQueryParams = route.screen == 'VerifyOtpScreen' || route.screen == 'CheckoutScreen';
        
        if (hasPathParams || needsQueryParams) {
          buffer.writeln("      builder: (context, state) {");
          
          // Extract path parameters
          if (route.path.contains(':chatId')) {
            buffer.writeln("        final chatId = state.pathParameters['chatId'] ?? '';");
            buffer.writeln("        return ${route.screen}(chatId: chatId);");
          } else if (route.path.contains(':transactionId')) {
            buffer.writeln("        final transactionId = state.pathParameters['transactionId'] ?? '';");
            buffer.writeln("        return ${route.screen}(transactionId: transactionId);");
          } else if (route.path.contains(':id') && route.name.contains('booking')) {
            buffer.writeln("        final bookingId = state.pathParameters['id'] ?? '';");
            buffer.writeln("        return ${route.screen}(bookingId: bookingId);");
          } else if (route.path.contains(':id') && route.name.contains('transaction')) {
            buffer.writeln("        final transactionId = state.pathParameters['id'] ?? '';");
            buffer.writeln("        return ${route.screen}(transactionId: transactionId);");
          } else if (route.screen == 'CheckoutScreen') {
            buffer.writeln("        final amountStr = state.uri.queryParameters['amount'] ?? '0.0';");
            buffer.writeln("        final amount = double.tryParse(amountStr) ?? 0.0;");
            buffer.writeln("        final orderId = state.uri.queryParameters['orderId'];");
            buffer.writeln("        return ${route.screen}(amount: amount, orderId: orderId);");
          } else {
            buffer.writeln("        return const ${route.screen}();");
          }
          buffer.writeln("      },");
        } else {
          buffer.writeln("      builder: (context, state) => const ${route.screen}(),");
        }
        buffer.writeln("    ),");
      }
    }
    
    buffer.writeln("  ],");
    buffer.writeln("  errorBuilder: (context, state) => Scaffold(");
    buffer.writeln("    appBar: AppBar(title: const Text('Error')),");
    buffer.writeln("    body: Center(");
    buffer.writeln("      child: Column(");
    buffer.writeln("        mainAxisAlignment: MainAxisAlignment.center,");
    buffer.writeln("        children: [");
    buffer.writeln("          const Icon(Icons.error_outline, size: 64, color: Colors.grey),");
    buffer.writeln("          const SizedBox(height: 16),");
    buffer.writeln("          Text('Page not found: \${state.uri.path}'),");
    buffer.writeln("          const SizedBox(height: 16),");
    buffer.writeln("          ElevatedButton(");
    buffer.writeln("            onPressed: () => context.go(AppRoutes.main),");
    buffer.writeln("            child: const Text('Go Home'),");
    buffer.writeln("          ),");
    buffer.writeln("        ],");
    buffer.writeln("      ),");
    buffer.writeln("    ),");
    buffer.writeln("  ),");
    buffer.writeln(");");
    
    // Redirect handler (only if needed)
    if (includeOnboarding || hasAuth) {
      buffer.writeln();
      buffer.writeln("/// Handle route redirects based on app state.");
      buffer.writeln("Future<String?> _handleRedirect(");
      buffer.writeln("  BuildContext context,");
      buffer.writeln("  GoRouterState state,");
      buffer.writeln(") async {");
      buffer.writeln("  final location = state.uri.path;");
      buffer.writeln();
      buffer.writeln("  // Handle initial route");
      buffer.writeln("  if (location == AppRoutes.initial || location == '/') {");
      if (includeSplash) {
        buffer.writeln("    return AppRoutes.splash;");
      } else if (includeOnboarding) {
        buffer.writeln("    // Check onboarding first");
        buffer.writeln("    final prefs = await SharedPreferences.getInstance();");
        buffer.writeln("    final onboardingCompleted = prefs.getBool('onboarding_completed') ?? false;");
        buffer.writeln("    if (!onboardingCompleted) {");
        buffer.writeln("      return AppRoutes.onboarding;");
        buffer.writeln("    }");
        if (hasAuth) {
          buffer.writeln("    // TODO: Check auth and redirect to login if needed");
          buffer.writeln("    return AppRoutes.main;");
        } else {
          buffer.writeln("    return AppRoutes.main;");
        }
      } else if (hasAuth) {
        buffer.writeln("    // TODO: Check auth and redirect to login if needed");
        buffer.writeln("    return AppRoutes.main;");
      } else {
        buffer.writeln("    return AppRoutes.main;");
      }
      buffer.writeln("  }");
      buffer.writeln();
      buffer.writeln("  // Don't redirect if already on target route");
      if (includeSplash) {
        buffer.writeln("  if (location == AppRoutes.splash) return null;");
      }
      if (includeOnboarding) {
        buffer.writeln("  if (location == AppRoutes.onboarding) return null;");
      }
      if (hasAuth) {
        buffer.writeln("  if (location == AppRoutes.login ||");
        buffer.writeln("      location == AppRoutes.signup ||");
        buffer.writeln("      location == AppRoutes.forgot_password ||");
        buffer.writeln("      location == AppRoutes.verify_otp) {");
        buffer.writeln("    return null;");
        buffer.writeln("  }");
      }
      buffer.writeln("  if (location == AppRoutes.main || location == AppRoutes.home) return null;");
      buffer.writeln();
      
      if (includeOnboarding) {
        buffer.writeln("  // Check onboarding completion for other routes");
        buffer.writeln("  final prefs = await SharedPreferences.getInstance();");
        buffer.writeln("  final onboardingCompleted = prefs.getBool('onboarding_completed') ?? false;");
        buffer.writeln();
        buffer.writeln("  if (!onboardingCompleted) {");
        buffer.writeln("    return AppRoutes.onboarding;");
        buffer.writeln("  }");
        buffer.writeln();
      }
      
      if (hasAuth) {
        buffer.writeln("  // Check authentication");
        buffer.writeln("  // TODO: Replace with actual auth check from provider");
        buffer.writeln("  // For now, allow all routes - implement auth check later");
        buffer.writeln("  // final container = ProviderScope.containerOf(context);");
        buffer.writeln("  // final isAuthenticated = container.read(isAuthenticatedProvider);");
        buffer.writeln("  // if (!isAuthenticated && location != AppRoutes.login) {");
        buffer.writeln("  //   return AppRoutes.login;");
        buffer.writeln("  // }");
        buffer.writeln();
      }
      
      buffer.writeln("  // Default: allow navigation");
      buffer.writeln("  return null;");
      buffer.writeln("}");
    }
    
    return buffer.toString();
  }
  
  static String _getScreenImportPath(String moduleName, String screenName) {
    return '../modules/$moduleName/presentation/screens/${_toSnakeCase(screenName)}.dart';
  }
  
  static String _toConstantName(String name) {
    return name
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceAll(RegExp(r'^_'), '')
        .replaceAll(RegExp(r'[^a-z0-9_]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .toLowerCase();
  }
  
  static String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceAll(RegExp(r'^_'), '')
        .toLowerCase();
  }
}
