/// Sample app generator for creating example apps.
library;

import '../config/app_config.dart';
import '../utils/console.dart';
import '../utils/file_utils.dart';
import 'project_generator.dart';

/// Generates a complete sample app with pre-configured modules.
class SampleAppGenerator {
  final AppConfig config;

  SampleAppGenerator(this.config);

  /// Generate a sample app with common modules.
  Future<bool> generate() async {
    try {
      Console.header('Generating Sample App');
      Console.info('This will create a complete example app with:');
      Console.listItem('Authentication module');
      Console.listItem('Wallet module');
      Console.listItem('Chat module');
      Console.listItem('Pre-configured routes and providers');
      Console.listItem('Environment configuration');
      Console.listItem('Sample tests');
      Console.blank();

      // Use ProjectGenerator with sample modules
      final sampleConfig = AppConfig(
        appName: config.appName,
        packageName: config.packageName,
        description: 'A sample Kiro app demonstrating module integration',
        organization: config.organization,
        platforms: config.platforms,
        modules: config.modules.isNotEmpty
            ? config.modules
            : [
                // Default sample modules
                KiroModule.auth,
                KiroModule.wallet,
                KiroModule.chat,
              ],
        stateManagement: config.stateManagement,
        primaryColor: config.primaryColor,
        useFirebase: config.useFirebase,
        initGit: config.initGit,
        outputDirectory: config.outputDirectory,
        locales: config.locales,
        defaultLocale: config.defaultLocale,
      );

      final generator = ProjectGenerator(sampleConfig);
      final success = await generator.generate();

      if (success) {
        // Generate sample README
        await _generateSampleReadme();
        Console.success('Sample app generated successfully!');
      }

      return success;
    } catch (e) {
      Console.error('Failed to generate sample app: $e');
      return false;
    }
  }

  /// Generate sample app README.
  Future<void> _generateSampleReadme() async {
    final content = '''
# ${config.appName} - Sample Kiro App

This is a sample application generated by KIRO CLI, demonstrating:

- **Authentication** - User login, signup, and OTP verification
- **Wallet** - Digital wallet with transactions
- **Chat** - Real-time messaging

## Getting Started

### Prerequisites

- Flutter SDK 3.0.0 or higher
- Dart SDK 3.0.0 or higher

### Installation

\`\`\`bash
# Install dependencies
flutter pub get

# Run the app
flutter run
\`\`\`

## Project Structure

\`\`\`
lib/
├── config/          # App configuration
│   ├── router.dart  # Auto-generated routes
│   └── theme.dart   # App theme
├── core/            # Core functionality
│   └── providers.dart  # Provider registry
├── modules/         # Feature modules
│   ├── auth/        # Authentication
│   ├── wallet/      # Digital wallet
│   └── chat/        # Messaging
└── main.dart        # App entry point
\`\`\`

## Modules

### Authentication Module

- Login screen: \`/login\`
- Signup screen: \`/signup\`
- Forgot password: \`/forgot-password\`
- OTP verification: \`/verify-otp\`

### Wallet Module

- Wallet screen: \`/wallet\`
- Add money: \`/wallet/add-money\`
- Transactions: \`/wallet/transactions\`

### Chat Module

- Chat list: \`/chat\`
- Chat detail: \`/chat/:id\`

## Environment Configuration

The app uses environment variables for configuration:

- \`.env.dev\` - Development environment
- \`.env.staging\` - Staging environment
- \`.env.prod\` - Production environment

Load environment:

\`\`\`dart
await EnvConfig.load(env: 'dev');
\`\`\`

## Testing

Run tests:

\`\`\`bash
flutter test
\`\`\`

## Building

### Android

\`\`\`bash
flutter build apk --release
\`\`\`

### iOS

\`\`\`bash
flutter build ios --release
\`\`\`

### Web

\`\`\`bash
flutter build web --release
\`\`\`

## CI/CD

This project includes CI/CD configuration:

- **GitHub Actions**: \`.github/workflows/ci.yml\`
- **GitLab CI**: \`.gitlab-ci.yml\`

## Next Steps

1. Configure Firebase (if enabled)
2. Set up environment variables
3. Customize theme and branding
4. Implement business logic
5. Add more modules as needed

## Resources

- [KIRO CLI Documentation](../KIRO_CLI_GUIDE.md)
- [Flutter Documentation](https://flutter.dev/docs)
- [Riverpod Documentation](https://riverpod.dev)

## Support

For issues and questions:
- Check [KIRO CLI Guide](../KIRO_CLI_GUIDE.md)
- Review [CLI Automation Pipeline](../CLI_AUTOMATION_PIPELINE.md)

Happy coding! 🚀
''';

    await FileUtils.writeFile(
      FileUtils.join(config.projectPath, 'README.md'),
      content,
    );
  }
}


